apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: openlibertydevfile
  name: openlibertydevfile
spec:
  replicas: 1
  selector:
    matchLabels:
      component: openlibertydevfile
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: openlibertydevfile
      name: openlibertydevfile
    spec:
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: jeevandroid/open-liberty-dev:latest
        imagePullPolicy: Always
        name: devruntime
        resources:
          limits:
            memory: 768Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/odo
          name: odo-volume
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      volumes:
      - name: odo-volume
        emptyDir: {}